(function(g){var window=this;'use strict';var Jlb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.Iab)("0",Math.max(0,b-c))+a},Klb=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Llb=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Nlb=function(a){"number"===typeof a?(this.date=Mlb(a,0,1),A6(this,1)):g.Xa(a)?(this.date=Mlb(a.getFullYear(),a.getMonth(),a.getDate()),A6(this,a.getDate())):(this.date=new Date(g.cb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),A6(this,a))},Mlb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},A6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},B6=function(a,b){g.tQ.call(this,a,{I:"div",
T:"ytp-reminder-menu",Y:{role:"menu",tabindex:"-1"},X:[{I:"div",T:"ytp-reminder-menu-contents",X:[{I:"div",T:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ha("ytp-reminder-menu-items");this.hide()},Plb=function(a){var b=Olb(a),c=0,d={};
for(c=0;c<b.length;d={KN:d.KN},c++){var e=a.j[c];e||(e=new g.W({I:"div",T:"ytp-reminder-menu-item",Y:{role:"menuitem",tabindex:"0"},X:[{I:"div",T:"ytp-reminder-menu-item-icon",Ba:"{{icon}}"},{I:"div",T:"ytp-reminder-menu-item-label",Ba:"{{text}}"}]}),d.KN=c,e.Ta("click",function(l){return function(){var m=l.KN;a.Ob();m=Olb(a)[m];a.va("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ga(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Klb();break;case "NOTIFICATIONS_NONE":h=Llb();break;case "NOTIFICATIONS_ACTIVE":h=g.esa()}f=f.text?g.wG(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Ob():a.xd(a.buttonElement)},Olb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},C6=function(a){g.W.call(this,{I:"div",
X:[{I:"button",Na:["ytp-offline-slate-button","ytp-button"],X:[{I:"div",T:"ytp-offline-slate-button-icon",Ba:"{{icon}}"},{I:"div",T:"ytp-offline-slate-button-text",Ba:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Ha("ytp-offline-slate-button"))&&this.V(this.buttonElement,"click",this.G);this.hide()},Rlb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.Q(c,Qlb)?a.upcomingEventReminderButtonRenderer=g.Q(c,Qlb):c&&g.Q(c,Qlb)||(a.upcomingEventReminderButtonRenderer=null);D6(a)},D6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.wG(b.toggledText):"";a.update({text:c,icon:Slb(b.toggledIcon)})}else c=b.defaultText?g.wG(b.defaultText):"",a.update({text:c,icon:Slb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Tlb(a))?(c=b.text?g.wG(b.text):"",a.update({text:c,icon:Slb(b.icon)}),a.show()):a.hide():a.hide()},Vlb=function(a,b,c){a.D||(a.D=new g.fE(a.J.W().Hl));
var d={context:g.CD(a.D.config_||g.BD())};g.IF()&&(d.context.clientScreenNonce=g.IF());d.params=c;g.gE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){Ulb(a)},
onTimeout:function(){Ulb(a)}})},Ulb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,D6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,D6(a))},Slb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Klb();case "NOTIFICATIONS_NONE":return Llb();case "NOTIFICATIONS_ACTIVE":return g.esa();default:return null}},Tlb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.v(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.Q(c.value,Wlb))&&c.state===b&&c.button&&g.Q(c.button,g.bP))return g.Q(c.button,g.bP);return null},Xlb=function(a){g.W.call(this,{I:"div",
T:"ytp-offline-slate",X:[{I:"div",T:"ytp-offline-slate-background"},{I:"div",T:"ytp-offline-slate-bar",X:[{I:"span",T:"ytp-offline-slate-icon",X:[{I:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},X:[{I:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",T:"ytp-offline-slate-messages",X:[{I:"div",T:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},Ba:"{{mainText}}"},{I:"div",T:"ytp-offline-slate-subtitle-text",Ba:"{{subtitleText}}"}]},{I:"span",T:"ytp-offline-slate-buttons"}]},{I:"button",Na:["ytp-offline-slate-close-button","ytp-button"],X:[g.zG()]},{I:"button",Na:["ytp-offline-slate-open-button","ytp-button"],X:[g.yG()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ha("ytp-offline-slate-background");
this.C=this.Ha("ytp-offline-slate-bar");this.G=new g.ar(function(){g.ir(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.ar(function(){g.ir(b.element,"ytp-offline-slate-collapsed")},15E3);
g.H(this,this.D);g.H(this,this.G);this.countdownTimer=new g.ar(this.f_,1E3,this);this.V(a,"presentingplayerstatechange",this.i_);this.V(a,"livestatedata",this.Sa);a=this.Ha("ytp-offline-slate-close-button");this.V(a,"click",function(){g.ir(b.element,"ytp-offline-slate-collapsed")});
a=this.Ha("ytp-offline-slate-open-button");this.V(a,"click",function(){g.kr(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Sa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Sl;var c=8===this.api.getPresentingPlayerType();g.mr(this.element,"ytp-offline-slate-premiere-trailer",a);g.mr(this.element,"ytp-offline-slate-hide-background",c)},Ylb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.wG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.wG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.mr(a.element,"ytp-offline-slate-single-text-line",!d);g.mr(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},E6=function(a,b){var c=(0,g.IC)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},fmb=function(a){g.CR.call(this,a);
var b=this;this.S=!1;this.ma=0;this.G=!1;this.B=new g.ar(function(){var e=b.player.W(),f=b.getVideoData();F6(b)&&(Zlb(b)?$lb(b,e,f):(amb(b),bmb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.Jj(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qa=new g.fE(void 0);this.ea=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Nlb).getTimezoneOffset();this.C=new g.KL(this);g.H(this,this.B);g.H(this,this.C);amb(this);cmb(this);this.C.V(a,"heartbeatparams",this.fE);this.C.V(a,"presentingplayerstatechange",this.E0);this.C.V(a,"videoplayerreset",this.F0);this.C.V(a,g.JP("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
dmb(this,void 0,this.j);var c=new g.IP(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.IP(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.yf([c,d]);emb(this)},emb=function(a){var b=a.getVideoData();
b.Ll&&(b=b.botguardData)&&g.qza(b,a.player.W())},amb=function(a){var b=a.getVideoData();
if(b.Ll&&(b=new g.mza(b),g.PI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Fk){var d=g.nza(b);if(d){c={};var e={};d=d.split("&");d=g.v(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=gmb[Number(e.r1c)]);c.challenge=b.videoData.Fk}}a.attestationResponse=c||void 0}},Zlb=function(a){var b=a.getVideoData();
if(!g.kP(a.getVideoData())||b.mZ)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.yM(b.K)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},hmb=function(a){if(Zlb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.kP(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Hl&&!b.ZB?!1:!!b.heartbeatToken},G6=function(a,b){if(!a.B.isActive()&&a.S){var c=a.getVideoData();
if(hmb(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().nX||6E4}else b=1E3;a.B.start(b)}}},lmb=function(a,b,c){b.Mm&&(c=g.fk(c,{internalipoverride:b.Mm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Cb&&(d.kpt=b.Cb);c=g.fk(c,d);g.DA(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&F6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=imb(e);if(f){a.player.Ua("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(jmb))?"0"===h[1]?0:1:-1;kmb(a,void 0,f,e,h)}},
onError:function(e){F6(a)&&H6(a,!0,"net-"+e.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")},
withCredentials:!0})},$lb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.fk(a.heartbeatParams.url,{request_id:g.Npa()});c.ra&&(e=g.fk(e,{vvt:c.ra}),c.mdxEnvironment&&(e=g.fk(e,{mdx_environment:c.mdxEnvironment})));g.PN(b,c.oauthToken).then(function(f){f&&(e=g.fk(e,{access_token:f}));lmb(a,c,e)})}},F6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.aH(a.player.Tb(a.getPlayerType()),4)?!1:hmb(a)||b.isLivePlayback?!0:(I6(a),!1)},bmb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.ra)?d:c.heartbeatServerData};a.ea=a.attestationResponse;c.Ll&&(e.attestationResponse=a.ea);var f=g.GP(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.IN(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=mmb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Hb())?void 0:g.RR(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=mmb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.N("enable_heartbeat_vod_playback_position")&&(l=nmb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.va("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&F6(a)){var q=a.getVideoData(),t=q.Ll&&null==a.ea,u;q.Ll=!(null==(u=p.heartbeatAttestationConfig)||!u.requiresAttestation)||
t;t=p.playabilityStatus;u=JSON.stringify(t)||"{}";p.authenticationMismatch&&a.player.Aa("authshear",{});var y=-1;var A=p.playabilityStatus;A&&(a.player.Ua("onHeartbeat",A),"OK"===A.status?y=p.stopHeartbeat?2:0:"UNPLAYABLE"===A.status?y=1:"LIVE_STREAM_OFFLINE"===A.status&&(y=0));a.sequenceNumber&&-1===y||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.ra=p.heartbeatServerData);q.hL=p;(A=p.playerCueRangeSet)&&g.nHa(q,A);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var E,L;(null==(E=p.progressBarConfig)?0:E.progressBarStartPosition)&&(null==(L=p.progressBarConfig)?0:L.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.va("dataupdated");kmb(a,p,t,u,y)}},
onError:function(p){F6(a)&&H6(a,!0,"net-"+p.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")}};
g.PN(b,g.AP(c)).then(function(p){p&&(n.gU="Bearer "+p);g.gE(a.qa,"player/heartbeat",e,n)})},kmb=function(a,b,c,d,e){-1===e?(c="decode "+g.dg(d,3),H6(a,!1,c)):2===e?(I6(a),a.G=!0):(a.ma=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.Vn(!0),a.player.Yg("heartbeat.stop",2,a.zf(d)),g.pC("heartbeatActionPlayerHalted",omb(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.Q(b,g.cP))&&pmb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):
(a.G=!0,d=0,a.D&&c&&(d=dmb(a,b,c),a.player.va("livestatedata",c)),d?G6(a,d):G6(a)))},dmb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=qmb(a,b,d);var f=a.getVideoData(),h=a.player.Tb(a.getPlayerType()),l=h.isPlaying()&&!g.oP(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.W().Ad()){var m,n=(null==(m=a.player.Af())?void 0:m.vc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.Aa("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.Q(d.streamTransitionEndpoint,g.cP);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&pmb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!f.hlsvp&&!f.kb||l){var p={video_id:f.videoId};f.qL&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.zd);p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=
f.Lm;p.ym=f.ym;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Em);f.ra&&(p.vvt=f.ra);d=void 0;f.hlsvp||f.kb?l&&(d=new E6("broadcastIdChanged",m+","+e),a.ZH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new E6("formatsReceived",""+e)),a.ZH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Fg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Ib&&a.api.YA()):g.bV(h)&&(f=(null==(p=a.player.Af())?void 0:p.vc())||{},a.player.Aa("hbse",f,!0),a.player.YA(),a.player.Ua("onLiveMediaEnded",c)));return b},qmb=function(a,b,c){return a.player.N("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},H6=function(a,b,c){var d=a.player.W();
if(!a.B.isActive()){a.B.stop();a.ma++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.HY||b&&!g.kP(a.getVideoData())&&!hmb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.OA)?h=a.heartbeatParams.OA:h=f.wX||5;f=a.ma>=h}f?(g.pC("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:omb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Yg(e,1,"Video playback interrupted. Please try again.",c):a.player.Yg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Hr(e,{msg:c}),G6(a,a.K.getValue()),g.Kj(a.K))}},omb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},I6=function(a){a.ma=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},cmb=function(a){var b=a.getVideoData(),c=a.player.W();
if(b.isLivePlayback)if(g.CDa(c.G)){a.D=!0;a.S=!0;if(!g.zN(c)||g.IN(c))a.offlineSlate=new Xlb(a.player),g.H(a,a.offlineSlate),g.jQ(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=qmb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?G6(a,d):G6(a,7500):G6(a,1E3))}else a.player.Yg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Cb(b.Ia,"heartbeat")&&a.player.Fg("heartbeat",a.getPlayerType())},pmb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.xo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.AP(a.getVideoData())),a.ZH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},mmb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},nmb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},imb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},rmb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},smb=rmb;smb=rmb;var gmb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Nlb.prototype;g.k.hV=smb.FIRSTDAYOFWEEK;g.k.iV=smb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new Nlb(this.date);a.hV=this.hV;a.iV=this.iV;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),A6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Jlb(Math.abs(a),b?6:4),Jlb(this.getMonth()+1,2),Jlb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var tmb=new g.Us("addUpcomingEventReminderEndpoint");var umb=new g.Us("removeUpcomingEventReminderEndpoint");var vmb=new g.Us("updateUpcomingEventReminderButtonStateCommand");var Qlb=new g.Us("upcomingEventReminderButtonRenderer"),Wlb=new g.Us("upcomingEventReminderButtonStateRenderer");g.x(B6,g.tQ);B6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.tQ.prototype.hide.call(this)};
B6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.tQ.prototype.show.call(this)};
B6.prototype.ya=function(){g.pb(this.j);g.tQ.prototype.ya.call(this)};g.x(C6,g.W);
C6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;D6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Ib)this.j.Ob();else{var b=Tlb(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.Q(null==b?void 0:b.command,g.iG))?void 0:a.commands)||[];a:{a=g.v(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.Q(c.value,
g.ucb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new B6(this.J,this.buttonElement),this.j.Ga(this.element),g.H(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;Plb(b)}};
C6.prototype.C=function(a){var b=g.Q(a,tmb),c=g.Q(a,umb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Vlb(this,e,d.params),a=g.v(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.Q(b,vmb)){this.B=g.Q(b,vmb).state;D6(this);break}}};g.x(Xlb,g.W);g.k=Xlb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Sa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.f_():Ylb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new C6(this.api),this.j.Ga(this.Ha("ytp-offline-slate-buttons")),g.H(this,this.j)),Rlb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Rlb(this.j,null,null);this.B=a}else this.B=null;this.i_()};
g.k.i_=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Tb(),d=this.getVideoData();b=d.isLivePlayback&&(g.bV(c)||g.aH(c,2)||g.aH(c,64));var e=2===d.autonavState&&g.aH(c,2);c=c.isPlaying()&&!g.oP(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Ib?(null==a?0:g.cH(a,2))&&!this.getVideoData().Sl&&(g.kr(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.kr(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.va("offlineslatestatechange"),
this.K&&this.api.YA()):this.Ib&&(this.hide(),this.api.va("offlineslatestatechange"))};
g.k.f_=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.cb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Ylb(this,e),this.countdownTimer.stop()):(Ylb(this,e,g.jH(b-a)),g.br(this.countdownTimer)))};
g.k.ya=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.ya.call(this)};E6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
E6.prototype.isExpired=function(){return 6E4<(0,g.IC)()-this.C};
E6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.x(fmb,g.CR);g.k=fmb.prototype;g.k.ya=function(){I6(this);this.player.mf("heartbeat");g.CR.prototype.ya.call(this)};
g.k.onCueRangeEnter=function(){this.S=!0;G6(this,2E3)};
g.k.fE=function(a){this.heartbeatParams=a;G6(this,2E3)};
g.k.E0=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.aH(a.state,2)||g.aH(a.state,64)?(I6(this),this.D&&(this.S=!0,G6(this,1E3))):(g.aH(a.state,1)||g.aH(a.state,8))&&G6(this,2E3))};
g.k.F0=function(){3!==this.player.getPresentingPlayerType()&&G6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.wl=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.ZH=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.pC("heartbeatActionPlayerTransitioned",a)};
g.k.zf=function(a){var b="LICENSE",c=imb(a);if(c)return c.reason||g.aS[b]||"";(a=a.match(jmb))&&(a=Number(a[1]))&&(b=g.pJa(a));return g.aS[b]||""};
g.k.zD=function(){return!!this.offlineSlate&&this.offlineSlate.Ib};
var jmb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.BR("heartbeat",fmb);})(_yt_player);
