(function(g){var window=this;'use strict';var wmb=function(a){g.W.call(this,{I:"div",T:"ytp-inline-preview-ui"});this.xg=!1;this.player=a;this.V(a,"onStateChange",this.XQ);this.V(a,"videodatachange",this.gx);this.V(a,"onInlinePreviewModeChange",this.K5);this.Bf=new g.Zq(this.qw,null,this);g.H(this,this.Bf)},J6=function(a){g.CR.call(this,a);
this.j=new wmb(this.player);g.H(this,this.j);this.j.hide();g.jQ(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.jr(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.x(wmb,g.W);g.k=wmb.prototype;
g.k.NN=function(){this.tooltip=new g.dU(this.player,this);g.H(this,this.tooltip);g.jQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.bd=new g.jS(this.player);g.H(this,this.bd);this.rk=new g.W({I:"div",Na:["ytp-inline-preview-scrim"]});g.H(this,this.rk);this.rk.Ga(this.element);this.V(this.rk.element,"click",this.II);this.Gj=new g.WT(this.player,this,300);g.H(this,this.Gj);this.Gj.Ga(this.rk.element);this.controls=new g.W({I:"div",T:"ytp-inline-preview-controls"});g.H(this,this.controls);
this.controls.Ga(this.element);var a=new g.nT(this.player,this,!1);g.H(this,a);a.Ga(this.controls.element);a=new g.UT(this.player,this);g.H(this,a);a.Ga(this.controls.element);this.Sc=new g.uT(this.player,this);g.H(this,this.Sc);g.jQ(this.player,this.Sc.element,4);this.V(this.player,"appresize",this.Mb);this.V(this.player,"fullscreentoggled",this.Mb);this.Mb()};
g.k.show=function(){g.$q(this.Bf);this.xg||(this.NN(),this.xg=!0);0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.Sc.show();this.player.Ua("onInlinePreviewUiReady")};
g.k.hide=function(){this.Bf.stop();g.W.prototype.hide.call(this);this.player.isInline()||this.xg&&this.Sc.hide()};
g.k.ya=function(){g.W.prototype.ya.call(this)};
g.k.II=function(a){a.target===this.rk.element&&this.player.Ua("onExpandInlinePreview",a)};
g.k.K5=function(){g.mr(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.bf=function(){this.Sc.Hc();this.Gj.Hc()};
g.k.qw=function(){this.bf();g.$q(this.Bf)};
g.k.Mb=function(){g.GT(this.Sc,0,this.player.qb().getPlayerSize().width,!1);g.vT(this.Sc)};
g.k.XQ=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.gx=function(a,b){if(this.player.isInline()){g.mr(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.XB);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.mr(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Ec=function(){return this.tooltip};
g.k.Mg=function(){return!1};
g.k.Ng=function(){return!1};
g.k.wm=function(){return!1};
g.k.HJ=function(){};
g.k.lq=function(){};
g.k.Wy=function(){};
g.k.hn=function(){return null};
g.k.eH=function(){return null};
g.k.fN=function(){return new g.ue(0,0)};
g.k.Ok=function(){return new g.vo(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Ew=function(a,b,c,d,e){var f=d=0,h=0,l=g.Jo(a);if(b){c=g.hr(b,"ytp-mute-button");var m=g.hr(b,"ytp-subtitles-button"),n=g.Ho(b,this.element);b=g.Jo(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.qb().getPlayerSize().width;h=g.pe(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Up=function(){};
g.k.mm=function(){return!1};
g.k.cF=function(){};
g.k.WA=function(){};
g.k.Gr=function(){};
g.k.Fr=function(){};
g.k.uy=function(){};
g.k.Ps=function(){};
g.k.NE=function(){};g.x(J6,g.CR);J6.prototype.wl=function(){return!1};
J6.prototype.load=function(){this.player.hideControls();this.j.show()};
J6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.BR("inline_preview",J6);})(_yt_player);
